version: '3.8'
services:
  api:
    container_name: 'go_shop_api'
    build: './'
    image: 'go_shop_api'
    ports: 
      - '8080:8080'
    depends_on: 
      - 'mongo'
    links:
      - mongo:mongo
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    volumes:
    - ./db:/data/db
    ports:
      - '27100:27017'